# Introduction to PyTorch
## This file copied by Michael Hudson
### What is PyTorch
An open source machine learning library for Python.

In [2]:
# import the module
import torch

PyTorch Tensors - a specialised data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model's parameters.
Construct a vector of 3 elements

In [3]:
# define a tensor object
x = torch.tensor([5.3, 2.1, -3.1])
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


In [4]:
x = torch.tensor([4.5, 2.3, -1.5, 2])
print(x)

tensor([ 4.5000,  2.3000, -1.5000,  2.0000])


Construct a matrix with specified values

In [5]:
A = torch.tensor([[5.3, 2.1], [0.2, 2.1]])
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


In [6]:
A = torch.tensor([[1.5, 2.0], [3.1, 4.2]])
print(A)

tensor([[1.5000, 2.0000],
        [3.1000, 4.2000]])


Construct a matrix with random or fixed values
- `torch.rand` - returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)
(https://pytorch.org/docs/stable/generated/torch.rand.html)
- `torch.zeros` - returns a tensor filled with the scalar value 0
(https://pytorch.org/docs/stable/generated/torch.zeros.html)
- `torch.ones` - returns a tensor filled with the scalar value 1
(https://pytorch.org/docs/stable/generated/torch.ones.html)

In [7]:
A = torch.rand(10, 2)
print(A)

tensor([[0.3639, 0.8036],
        [0.6743, 0.8346],
        [0.8452, 0.2515],
        [0.0393, 0.5910],
        [0.7767, 0.5257],
        [0.2228, 0.1938],
        [0.2706, 0.6423],
        [0.3103, 0.3193],
        [0.8491, 0.4736],
        [0.8741, 0.5526]])


In [8]:
A = torch.rand(10, 3)
print(A)

tensor([[0.4664, 0.1584, 0.8527],
        [0.2163, 0.5872, 0.5053],
        [0.0083, 0.0244, 0.2549],
        [0.3137, 0.4840, 0.8434],
        [0.4468, 0.8703, 0.2451],
        [0.3444, 0.6102, 0.5986],
        [0.4510, 0.8998, 0.7473],
        [0.3252, 0.9323, 0.6706],
        [0.2416, 0.8035, 0.9316],
        [0.7113, 0.3348, 0.9712]])


In [9]:
A = torch.zeros(10, 2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [10]:
A = torch.ones(10, 3)
print(A)
A[:, 1] = 0
print(A)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


Attributes of a Tensor
- `torch.Tensor.size` - returns the size of the self tensor. If dim is not specified, the returned value is a torch.Size, a subclass of tuple. If dim is specified, returns an int holding the size of that dimension. (https://pytorch.org/docs/stable/generated/torch.Tensor.size.html)
- `torch.Tensor.dim` - returns the number of dimensions of self tensor. (https://pytorch.org/docs/stable/generated/torch.Tensor.dim.html)
- `torch.Tensor.type` - returns the type if dtype is not provided, else casts this object to the specified type. (https://pytorch.org/docs/stable/generated/torch.Tensor.type.html)

In [11]:
B = torch.rand(5, 2, 2)
print(B)

tensor([[[0.8121, 0.0964],
         [0.1227, 0.1872]],

        [[0.4208, 0.5071],
         [0.2934, 0.1153]],

        [[0.0154, 0.9603],
         [0.4932, 0.1871]],

        [[0.0243, 0.1066],
         [0.9187, 0.3779]],

        [[0.4926, 0.8556],
         [0.8343, 0.9527]]])


In [12]:
C = torch.rand(5, 3, 3)
print(C)

tensor([[[0.2682, 0.9569, 0.2668],
         [0.4098, 0.5896, 0.1608],
         [0.7380, 0.7781, 0.4695]],

        [[0.5514, 0.0134, 0.2366],
         [0.4457, 0.7697, 0.7052],
         [0.2361, 0.5845, 0.0233]],

        [[0.3697, 0.9173, 0.2249],
         [0.0916, 0.8970, 0.1201],
         [0.1968, 0.4631, 0.3273]],

        [[0.4343, 0.3417, 0.6172],
         [0.6975, 0.3484, 0.1090],
         [0.5101, 0.0586, 0.8102]],

        [[0.4446, 0.3405, 0.1535],
         [0.2925, 0.1110, 0.8884],
         [0.0117, 0.8808, 0.3213]]])


In [13]:
B.size()

torch.Size([5, 2, 2])

In [14]:
B.dim()

3

In [15]:
B.type()

'torch.FloatTensor'

In [16]:
C.size()

torch.Size([5, 3, 3])

In [17]:
C.type()

'torch.FloatTensor'

In [18]:
C.dim()

3

Arithmetic operations of tensors
- Addition - `+`
- Subtraction - `-`
- Multiplication
  - Elementwise product: `*` or `torch.mul`
  - Matrix multiplication: `torch.matmul` or `torch.mm`
- Division - `/`

Tips
- Check tensor sizes for algebra computations like multiplication `torch.mm(X1, X2)` with `X1.size()`, `X2.size()`. Refer to **Broadcasting Semantics** for details: (https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics).
- Check tensor type for data manipulations with `X.type()`

In [19]:
A = torch.rand(2, 2)
B = torch.rand(2, 2)

C = 2 * B
D = A + C
E = A * B

print("A: ", A)
print("")
print("B: ", B)
print("")
print("C: ", C)
print("")
print("D: ", D)
print("")
print("E: ", E)

A:  tensor([[0.0366, 0.2541],
        [0.1342, 0.7612]])

B:  tensor([[0.6944, 0.8117],
        [0.9060, 0.2517]])

C:  tensor([[1.3887, 1.6235],
        [1.8120, 0.5034]])

D:  tensor([[1.4253, 1.8776],
        [1.9462, 1.2646]])

E:  tensor([[0.0254, 0.2063],
        [0.1216, 0.1916]])


In [20]:
A = torch.rand(2, 2)
B = torch.rand(2, 2)

C = A * B
D = C + B
E = C - A

print("A: ", A)
print("")
print("B: ", B)
print("")
print("C: ", C)
print("")
print("D: ", D)
print("")
print("E: ", E)

A:  tensor([[0.6294, 0.7422],
        [0.0174, 0.8870]])

B:  tensor([[0.4169, 0.4340],
        [0.7150, 0.5805]])

C:  tensor([[0.2624, 0.3221],
        [0.0124, 0.5149]])

D:  tensor([[0.6793, 0.7561],
        [0.7275, 1.0954]])

E:  tensor([[-0.3670, -0.4201],
        [-0.0050, -0.3721]])


Other tensor operations and functions

- `torch.arange` - returns a 1-D tensor of size (end - start)/step with values from the interval [start, end] taken with common difference step beginning from start. (https://pytorch.org/docs/stable/generated/torch.arange.html)

- `torch.randperm` - returns a random permutation of integers from 0 to n-1. (https://pytorch.org/docs/stable/generated/torch.randperm.html)

- `torch.Tensor.view` - returns a new tensor with the same data as the self tensor but of a different shape. (https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) *Note that the original tensor x was NOT modified*

- `torch.Tensor.to` - returns a Tensor with the specified dtype. (https://pytorch.org/docs/stable/generated/torch.Tensor.to.html#torch.Tensor.to)

- Indexing and slicing - `tensor[0]` returns the first row, `tensor[:, 0]` returns the first column

- Updating values in a tensor - `tensor[:, 1] = 0` sets the second column to value 1

In [21]:
x = torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [22]:
x = torch.arange(5)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4])
torch.LongTensor


In [23]:
x = torch.randperm(5)
print(x)
print(x.type())

tensor([1, 2, 4, 0, 3])
torch.LongTensor


In [24]:
x = torch.randperm(10)
print(x)
print(x.type())

tensor([5, 7, 3, 0, 4, 9, 8, 6, 2, 1])
torch.LongTensor


In [25]:
x = torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [26]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [27]:
print(x.view(2, 5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [28]:
print(x.view(5, 2))

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [29]:
# the original tensor x remains unchanged
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [30]:
# create a new tensor y to store the reshaped tensor x
y = x.view(5, 2)

print("x: ", x)
print("")
print("y: ", y)

x:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

y:  tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [31]:
y = y.to(torch.float64)
print(y)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]], dtype=torch.float64)


In [32]:
print(y[0])

tensor([0., 1.], dtype=torch.float64)


In [33]:
print(y[1])

tensor([2., 3.], dtype=torch.float64)


In [34]:
v = y[2]
print(v)

tensor([4., 5.], dtype=torch.float64)


In [35]:
print(y[1:4])

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]], dtype=torch.float64)


In [36]:
idx = 1
n = 3

print(y[idx : idx + n])

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]], dtype=torch.float64)


In [37]:
z = y[1 : 1 + 3]
print(z)

print("")

print("dimension=", z.dim())
print(z.size())

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]], dtype=torch.float64)

dimension= 2
torch.Size([3, 2])


In [38]:
v = y[1]
print(v)

print("")

print("dimension=", v.dim())
print(v.size())

tensor([2., 3.], dtype=torch.float64)

dimension= 1
torch.Size([2])


In [39]:
print(z)
z[:, 1] = 4
print(z)

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]], dtype=torch.float64)
tensor([[2., 4.],
        [4., 4.],
        [6., 4.]], dtype=torch.float64)


this code taken with modification from Xavier Bresson, NUS under MIT licence

In [40]:
torch.__version__

'2.8.0+cu129'