# Introduction to PyTorch
## This file copied by Michael Hudson
### What is PyTorch
An open source machine learning library for Python.

In [1]:
# import the module
import torch

PyTorch Tensors - a specialised data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model's parameters.
Construct a vector of 3 elements

In [2]:
# define a tensor object
x = torch.tensor([5.3, 2.1, -3.1])
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


In [3]:
x = torch.tensor([4.5, 2.3, -1.5, 2])
print(x)

tensor([ 4.5000,  2.3000, -1.5000,  2.0000])


Construct a matrix with specified values

In [4]:
A = torch.tensor([[5.3, 2.1], [0.2, 2.1]])
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


In [5]:
A = torch.tensor([[1.5, 2.0], [3.1, 4.2]])
print(A)

tensor([[1.5000, 2.0000],
        [3.1000, 4.2000]])


Construct a matrix with random or fixed values
- `torch.rand` - returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)
(https://pytorch.org/docs/stable/generated/torch.rand.html)
- `torch.zeros` - returns a tensor filled with the scalar value 0
(https://pytorch.org/docs/stable/generated/torch.zeros.html)
- `torch.ones` - returns a tensor filled with the scalar value 1
(https://pytorch.org/docs/stable/generated/torch.ones.html)

In [6]:
A = torch.rand(10, 2)
print(A)

tensor([[0.2657, 0.9892],
        [0.4246, 0.2396],
        [0.8476, 0.7504],
        [0.1289, 0.0515],
        [0.7309, 0.5883],
        [0.9416, 0.5218],
        [0.6238, 0.6773],
        [0.8438, 0.7929],
        [0.6230, 0.9505],
        [0.9723, 0.7577]])


In [7]:
A = torch.rand(10, 3)
print(A)

tensor([[0.6184, 0.1100, 0.5257],
        [0.6420, 0.6256, 0.7248],
        [0.4681, 0.1568, 0.3778],
        [0.0602, 0.7436, 0.2420],
        [0.6754, 0.5832, 0.8399],
        [0.5841, 0.1865, 0.7701],
        [0.6351, 0.1927, 0.6729],
        [0.1803, 0.9245, 0.5901],
        [0.5284, 0.0152, 0.9698],
        [0.4239, 0.3933, 0.7191]])


In [9]:
A = torch.zeros(10, 2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [22]:
A = torch.ones(10, 3)
print(A)
A[:, 1] = 0
print(A)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.],
        [1., 0., 1.]])


Attributes of a Tensor
- `torch.Tensor.size` - returns the size of the self tensor. If dim is not specified, the returned value is a torch.Size, a subclass of tuple. If dim is specified, returns an int holding the size of that dimension. (https://pytorch.org/docs/stable/generated/torch.Tensor.size.html)
- `torch.Tensor.dim` - returns the number of dimensions of self tensor. (https://pytorch.org/docs/stable/generated/torch.Tensor.dim.html)
- `torch.Tensor.type` - returns the type if dtype is not provided, else casts this object to the specified type. (https://pytorch.org/docs/stable/generated/torch.Tensor.type.html)

In [11]:
B = torch.rand(5, 2, 2)
print(B)

tensor([[[0.8801, 0.0409],
         [0.6446, 0.4188]],

        [[0.1819, 0.2604],
         [0.9541, 0.2302]],

        [[0.3273, 0.7806],
         [0.0587, 0.9029]],

        [[0.7097, 0.2613],
         [0.2945, 0.0705]],

        [[0.0240, 0.5795],
         [0.4577, 0.4694]]])


In [12]:
C = torch.rand(5, 3, 3)
print(C)

tensor([[[0.7654, 0.0515, 0.4692],
         [0.1765, 0.2156, 0.9284],
         [0.8509, 0.6361, 0.5469]],

        [[0.0380, 0.4264, 0.2363],
         [0.8436, 0.3405, 0.7450],
         [0.1256, 0.8935, 0.1176]],

        [[0.5021, 0.2333, 0.5198],
         [0.7793, 0.9656, 0.7088],
         [0.0413, 0.5024, 0.6372]],

        [[0.1093, 0.8318, 0.8035],
         [0.9164, 0.0210, 0.1169],
         [0.0411, 0.2325, 0.1271]],

        [[0.2750, 0.6923, 0.8362],
         [0.3193, 0.2008, 0.2856],
         [0.7797, 0.1916, 0.1927]]])


In [13]:
B.size()

torch.Size([5, 2, 2])

In [14]:
B.dim()

3

In [15]:
B.type()

'torch.FloatTensor'

In [16]:
C.size()

torch.Size([5, 3, 3])

In [17]:
C.type()

'torch.FloatTensor'

In [18]:
C.dim()

3

Arithmetic operations of tensors
- Addition - `+`
- Subtraction - `-`
- Multiplication
  - Elementwise product: `*` or `torch.mul`
  - Matrix multiplication: `torch.matmul` or `torch.mm`
- Division - `/`

Tips
- Check tensor sizes for algebra computations like multiplication `torch.mm(X1, X2)` with `X1.size()`, `X2.size()`. Refer to **Broadcasting Semantics** for details: (https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics).
- Check tensor type for data manipulations with `X.type()`

In [19]:
A = torch.rand(2, 2)
B = torch.rand(2, 2)

C = 2 * B
D = A + C
E = A * B

print("A: ", A)
print("")
print("B: ", B)
print("")
print("C: ", C)
print("")
print("D: ", D)
print("")
print("E: ", E)

A:  tensor([[0.9241, 0.0110],
        [0.2890, 0.3500]])

B:  tensor([[0.8781, 0.2158],
        [0.4983, 0.2876]])

C:  tensor([[1.7561, 0.4316],
        [0.9966, 0.5751]])

D:  tensor([[2.6802, 0.4427],
        [1.2855, 0.9251]])

E:  tensor([[0.8114, 0.0024],
        [0.1440, 0.1006]])


In [20]:
A = torch.rand(2, 2)
B = torch.rand(2, 2)

C = A * B
D = C + B
E = C - A

print("A: ", A)
print("")
print("B: ", B)
print("")
print("C: ", C)
print("")
print("D: ", D)
print("")
print("E: ", E)

A:  tensor([[0.5802, 0.1614],
        [0.4006, 0.6998]])

B:  tensor([[0.9918, 0.4050],
        [0.0949, 0.2636]])

C:  tensor([[0.5754, 0.0654],
        [0.0380, 0.1845]])

D:  tensor([[1.5672, 0.4704],
        [0.1329, 0.4481]])

E:  tensor([[-0.0047, -0.0960],
        [-0.3626, -0.5154]])


Other tensor operations and functions
- `torch.arange` - returns a 1-D tensor of size (end - start)/step with values from the interval [start, end] taken with common difference step beginning from start. (https://pytorch.org/docs/stable/generated/torch.arange.html)
- `torch.randperm` - returns a random permutation of integers from 0 to n-1. (https://pytorch.org/docs/stable/generated/torch.randperm.html)
- `torch.Tensor.view` - returns a new tensor with the same data as the self tensor but of a different shape. (https://pytorch.org/docs/stable/generated/torch.Tensor.view.html) *Note that the original tensor x was NOT modified*
- `torch.Tensor.to` - returns a Tensor with the specified dtype. (https://pytorch.org/docs/stable/generated/torch.Tensor.to.html#torch.Tensor.to)
- Indexing and slicing - `tensor[0]` returns the first row, `tensor[:, 0]` returns the first column
- Updating values in a tensor - `tensor[:, 1] = 0` sets the second column to value 1

In [23]:
x = torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [24]:
x = torch.arange(5)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4])
torch.LongTensor


In [25]:
x = torch.randperm(5)
print(x)
print(x.type())

tensor([4, 3, 0, 2, 1])
torch.LongTensor


In [26]:
x = torch.randperm(10)
print(x)
print(x.type())

tensor([2, 6, 9, 1, 3, 0, 8, 5, 4, 7])
torch.LongTensor


In [27]:
x = torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [28]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [29]:
print(x.view(2, 5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [30]:
print(x.view(5, 2))

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [31]:
# the original tensor x remains unchanged
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [32]:
# create a new tensor y to store the reshaped tensor x
y = x.view(5, 2)

print("x: ", x)
print("")
print("y: ", y)

x:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

y:  tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [33]:
y = y.to(torch.float64)
print(y)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]], dtype=torch.float64)


In [34]:
print(y[0])

tensor([0., 1.], dtype=torch.float64)


In [35]:
print(y[1])

tensor([2., 3.], dtype=torch.float64)


In [36]:
v = y[2]
print(v)

tensor([4., 5.], dtype=torch.float64)


In [37]:
print(y[1:4])

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]], dtype=torch.float64)


In [38]:
idx = 1
n = 3

print(y[idx : idx + n])

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]], dtype=torch.float64)


In [39]:
z = y[1 : 1 + 3]
print(z)

print("")

print("dimension=", z.dim())
print(z.size())

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]], dtype=torch.float64)

dimension= 2
torch.Size([3, 2])


In [40]:
v = y[1]
print(v)

print("")

print("dimension=", v.dim())
print(v.size())

tensor([2., 3.], dtype=torch.float64)

dimension= 1
torch.Size([2])


In [41]:
print(z)
z[:, 1] = 4
print(z)

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]], dtype=torch.float64)
tensor([[2., 4.],
        [4., 4.],
        [6., 4.]], dtype=torch.float64)


this code taken with modification from Xavier Bresson, NUS under MIT licence