# Introduction to PyTorch

### What is PyTorch

An open source machine learning library for Python.

In [1]:
# import the module
import torch

### PyTorch Tensors - a specialized data structure that are very similar to arrays and matrices. In PyTorch, we use tensors to **encode the inputs and outputs** of a model, as well as the model’s **parameters**.

### Construct a vector of 3 elements

In [2]:
# define a Tensor object
x = torch.Tensor( [5.3 , 2.1 , -3.1 ] )
print(x)

tensor([ 5.3000,  2.1000, -3.1000])


In [3]:
x = torch.Tensor([4.5,2.3,-1.5, 2])
print(x)

tensor([ 4.5000,  2.3000, -1.5000,  2.0000])


### Construct a matrix with specified values 

In [4]:
A = torch.Tensor([[5.3,2.1] , [0.2,2.1]])
print(A)

tensor([[5.3000, 2.1000],
        [0.2000, 2.1000]])


In [5]:
A = torch.Tensor([[1.5,2.0],[3.1,4.2]])
print(A)

tensor([[1.5000, 2.0000],
        [3.1000, 4.2000]])


### Construct a matrix with random or fixed values


*   `torch.rand` - returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1) (https://pytorch.org/docs/stable/generated/torch.rand.html)

*   `torch.zeros` - returns a tensor filled with the scalar value 0 (https://pytorch.org/docs/stable/generated/torch.zeros.html)

*   `torch.ones` - returns a tensor filled with the scalar value 1 (https://pytorch.org/docs/stable/generated/torch.ones.html)



In [6]:
A = torch.rand(10,2)
print(A)

tensor([[0.7253, 0.2243],
        [0.0974, 0.2242],
        [0.2493, 0.3605],
        [0.8520, 0.6316],
        [0.2090, 0.6054],
        [0.2257, 0.5603],
        [0.2057, 0.4976],
        [0.4873, 0.2555],
        [0.7061, 0.2092],
        [0.5303, 0.1305]])


In [7]:
A = torch.rand(10,3)
print(A)

tensor([[0.5774, 0.8641, 0.4476],
        [0.9373, 0.3569, 0.8751],
        [0.9361, 0.9212, 0.3660],
        [0.8029, 0.0509, 0.6409],
        [0.7482, 0.8379, 0.5744],
        [0.4315, 0.3382, 0.4068],
        [0.4257, 0.8645, 0.1402],
        [0.2896, 0.6241, 0.0950],
        [0.5808, 0.8486, 0.2659],
        [0.7549, 0.9302, 0.2331]])


In [8]:
A = torch.zeros(10,2)
print(A)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [9]:
A = torch.ones(10,3)
print(A)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


### Attributes of a Tensor


*   `torch.Tensor.size` - returns the size of the self tensor. If dim is not specified, the returned value is a torch.Size, a subclass of tuple. If dim is specified, returns an int holding the size of that dimension. (https://pytorch.org/docs/stable/generated/torch.Tensor.size.html)

*   `torch.Tensor.dim` - returns the number of dimensions of self tensor. (https://pytorch.org/docs/stable/generated/torch.Tensor.dim.html)

*   `torch.Tensor.type` - returns the type if dtype is not provided, else casts this object to the specified type. (https://pytorch.org/docs/stable/generated/torch.Tensor.type.html)


In [10]:
B = torch.rand(5, 2, 2)
print(B)

tensor([[[0.3747, 0.2252],
         [0.4607, 0.2557]],

        [[0.1633, 0.0749],
         [0.9836, 0.3497]],

        [[0.3337, 0.8885],
         [0.8007, 0.5823]],

        [[0.9315, 0.7390],
         [0.5537, 0.2209]],

        [[0.4882, 0.6331],
         [0.9085, 0.4796]]])


In [11]:
C = torch.rand(5, 3, 3)
print(C)

tensor([[[0.4442, 0.8974, 0.8058],
         [0.6639, 0.8748, 0.8563],
         [0.0291, 0.3273, 0.1143]],

        [[0.9410, 0.4702, 0.8266],
         [0.3933, 0.1658, 0.6689],
         [0.1182, 0.6391, 0.4515]],

        [[0.2747, 0.0757, 0.1546],
         [0.6373, 0.2693, 0.7840],
         [0.5776, 0.3845, 0.6499]],

        [[0.9160, 0.9215, 0.9001],
         [0.9440, 0.9246, 0.7863],
         [0.7648, 0.3016, 0.0702]],

        [[0.0772, 0.4450, 0.1668],
         [0.1687, 0.9910, 0.2129],
         [0.8259, 0.3363, 0.4531]]])


In [12]:
B.size()

torch.Size([5, 2, 2])

In [13]:
B.dim()

3

In [14]:
B.type()

'torch.FloatTensor'

In [15]:
C.size()

torch.Size([5, 3, 3])

In [16]:
C.type()


'torch.FloatTensor'

In [17]:
C.dim()

3

### Arithmetic operations of tensors


*   Addition - `+`
*   Subtraction - `-`
*   Multiplication
  *   Elementwise product: `*` or `torch.mul`
  *   Matrix multiplication: `torch.matmul` or `torch.mm`

*   Division - `/`

### *Tips*

*   Check tensor sizes for algebra computations like multiplication `torch.mm(X1, X2)` with `X1.size()`, `X2.size()`. Refer to **Broadcasting Semantics** for details: https://pytorch.org/docs/stable/notes/broadcasting.html#broadcasting-semantics.
*   Check tensor type for data manipulations with `X.type()`







In [18]:
A = torch.rand(2,2)
B = torch.rand(2,2)

C = 2*B
D = A+C
E = A*B

print("A: ", A)
print('')
print("B: ", B)
print('')
print("C: ", C)
print('')
print("D: ", D)
print('')
print("E: ", E)

A:  tensor([[0.2547, 0.5865],
        [0.4075, 0.1974]])

B:  tensor([[0.0120, 0.7581],
        [0.4726, 0.9785]])

C:  tensor([[0.0240, 1.5162],
        [0.9453, 1.9570]])

D:  tensor([[0.2787, 2.1027],
        [1.3527, 2.1544]])

E:  tensor([[0.0031, 0.4446],
        [0.1926, 0.1931]])


In [19]:
A = torch.rand(2,2)
B = torch.rand(2,2)

C = A*B
D = C+B
E = C-A

print("A: ", A)
print('')
print("B: ", B)
print('')
print("C: ", C)
print('')
print("D: ", D)
print('')
print("E: ", E)

A:  tensor([[0.9786, 0.8607],
        [0.7553, 0.1266]])

B:  tensor([[0.7590, 0.6201],
        [0.0495, 0.6913]])

C:  tensor([[0.7428, 0.5337],
        [0.0374, 0.0875]])

D:  tensor([[1.5018, 1.1538],
        [0.0868, 0.7788]])

E:  tensor([[-0.2358, -0.3270],
        [-0.7179, -0.0391]])


### Other tensor operations and functions

*   `torch.arange` - returns a 1-D tensor of size (end - start)/step with values from the interval [start, end] taken with common difference step beginning from start. (https://pytorch.org/docs/stable/generated/torch.arange.html)

*   `torch.randperm` - returns a random permutation of integers from 0 to n - 1.(https://pytorch.org/docs/stable/generated/torch.randperm.html)

*   `torch.Tensor.view` - returns a new tensor with the same data as the self tensor but of a different shape. (https://pytorch.org/docs/stable/generated/torch.Tensor.view.html). *Note that the original tensor x was NOT modified*

* `torch.Tensor.to` - returns a Tensor with the specified dtype. (https://pytorch.org/docs/stable/generated/torch.Tensor.to.html#torch.Tensor.to)

*   Indexing and slicing - `tensor[0]` returns the first row, `tensor[:, 0]` returns the first column

*   Updating values in a tensor - ` tensor[:, 1] = 0` sets the second column to value 1



In [20]:
x = torch.arange(10)
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [21]:
x = torch.arange(5) 
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4])
torch.LongTensor


In [22]:
x = torch.randperm(5)
print(x)
print(x.type())

tensor([4, 2, 1, 3, 0])
torch.LongTensor


In [23]:
x = torch.randperm(10)
print(x)
print(x.type())

tensor([3, 1, 8, 5, 4, 7, 9, 6, 0, 2])
torch.LongTensor


In [24]:
x = torch.arange(10).long()
print(x)
print(x.type())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.LongTensor


In [25]:
x = torch.arange(10)
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [26]:
print(x.view(2, 5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [27]:
print(x.view(5, 2))

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [28]:
# the original tensor x remains unchanged
print(x)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [29]:
# create a new tensor y to store the reshaped tensor x
y = x.view(5,2)

print("x: ", x)
print('')
print("y: ", y)

x:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

y:  tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [30]:
y = y.to(torch.float64)

In [31]:
print(y)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]], dtype=torch.float64)


In [32]:
print(y[0])

tensor([0., 1.], dtype=torch.float64)


In [33]:
print(y[1])

tensor([2., 3.], dtype=torch.float64)


In [34]:
v = y[2]
print(v)

tensor([4., 5.], dtype=torch.float64)


In [35]:
print(y[1:4])

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]], dtype=torch.float64)


In [36]:
idx = 1
n=3

print( y[idx:idx+n] )

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]], dtype=torch.float64)


In [37]:
z = y[1: 1+3]
print(z)

print('')

print('dimension=',z.dim())
print(z.size())

tensor([[2., 3.],
        [4., 5.],
        [6., 7.]], dtype=torch.float64)

dimension= 2
torch.Size([3, 2])


In [38]:
v = y[1]
print(v)

print('')


print('dimension=',v.dim())
print(v.size())

tensor([2., 3.], dtype=torch.float64)

dimension= 1
torch.Size([2])


In [39]:
# change the second column values in z to 4
z[:, 1] = 4
print(z)

tensor([[2., 4.],
        [4., 4.],
        [6., 4.]], dtype=torch.float64)


##### this code is taken with modification from Xavier Bresson, NUS under MIT licence